set-executionpolicy remotesigned -scope currentuser
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
scoop help
scoop bucket add Ash258 https://github.com/Ash258/Scoop-Ash258.git
scoop bucket add extras
scoop bucket add dorado
scoop bucket add nerd-fonts
scoop bucket add nonportable
scoop bucket add php
scoop bucket add JetBrains
scoop bucket add spotify https://github.com/TheRandomLabs/Scoop-Spotify.git
scoop bucket add nirsoft
scoop bucket add scoop-bucket https://github.com/dodorz/scoop-bucket

# SIG # Begin signature block
# MIIFpwYJKoZIhvcNAQcCoIIFmDCCBZQCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUeLADDwInpHhFyrA09qeRPBWQ
# 2megggM5MIIDNTCCAiGgAwIBAgIQsMWWmUPDRIxO40WEZmkCMjAJBgUrDgMCHQUA
# MCMxITAfBgNVBAMTGE1vc3NlclBvd2VyU2hlbGxUZXN0Q2VydDAeFw0yMDA1MjUx
# MzE4MzlaFw0zOTEyMzEyMzU5NTlaMCMxITAfBgNVBAMTGE1vc3NlclBvd2VyU2hl
# bGxUZXN0Q2VydDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMquVzur
# iNrrNYdNgrlZ3kbZcGSZ/uaBGJmPoB72/4e3GDSR+Pdr5YQp6rnnYhRP7B2PVl3t
# iFL4gqeby8EEMq1FLEiPYaXeLxWO85yfAiN4sNgiI3IhVZdkMBnV+H1h5MSGA7zF
# G1JZKn8pZ9ZmCHtZMjQjqghFOx8CJ6TxApo/bgwZu3xK7vj18FiOEljijcnLMeVK
# +3o+ZZY0HKrDidZ4q74H/rF9gSRn/QFUDi8KUg43ifQLgt6L9OZvQ6/ofTUoEjx5
# ADstXaxCLfQw4jaDVFtx5QVk6JT9Do1W4VQEVCCncyq/vgIZ3QqZMUT++FGVl9z1
# 4+mVTJwRxEDMLKECAwEAAaNtMGswEwYDVR0lBAwwCgYIKwYBBQUHAwMwVAYDVR0B
# BE0wS4AQ9DNeBxK71HvQPW5n1S0+1aElMCMxITAfBgNVBAMTGE1vc3NlclBvd2Vy
# U2hlbGxUZXN0Q2VydIIQsMWWmUPDRIxO40WEZmkCMjAJBgUrDgMCHQUAA4IBAQBf
# D7wE5oKOsegB+XkgDcDIKry5bN45By8Rd9qLbNzn9Oz0teSOxaDi/ul+Dna7cfRB
# /Hw7DLcIkNFVplEqDjIq8+yJGO2dzJ1KljFlzunQ3UDFkR4h9ibDRXWJ/qbjlkSJ
# uojZeGmJtRa8EV4BZMqUEx3sPTRSoauwUG7olW3P4W6+F91fa0Vm/9yWNUwsJbGk
# O3t3X2eyB4ZozbWOYiJRK97/IQPo5Cz2nsg/lTtXiLTFM79PPfuUflVXfclSRasT
# YEBpN6TQwmlrIAWV+cZeVrx5y5AaE1KblsTY4SIB2y7eot3HvV4dugXGBuajxvW1
# 0DAi93R0kao4VqznxwbJMYIB2DCCAdQCAQEwNzAjMSEwHwYDVQQDExhNb3NzZXJQ
# b3dlclNoZWxsVGVzdENlcnQCELDFlplDw0SMTuNFhGZpAjIwCQYFKw4DAhoFAKB4
# MBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQB
# gjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkE
# MRYEFOTKThyDZJ4FFktVx/V3vrTYkISyMA0GCSqGSIb3DQEBAQUABIIBAELbZaHe
# o9OCg4jHYXkJAkTeKsviox2K/Nr0nHGQZ6Qik3JABZgrLTL9brt+i/7c0xcgI+w1
# IPRiZN+iBkdb8M6qG4Vt4AFpoSEwp6O6R3zSQfZVLyo83RfMAoIMfWqwpAdi1uAy
# cNHzW/ygRTjY/h20skYWOQW2zZR87AhUwFtVm/8sIe8dmcnkHRDx1xqX5i+ve8Uw
# sRncp0iKK3o5+kZgcU48LhDoopVzJ4mjO0IY9mIBMNCUiBOCNZbTaYNXw389fP5H
# IYzMWTH1xdP5MXPWfZpEPeKGE3K9mYfIHy3GyR+n/RCycUn+LgPuGoyv6bI+THQR
# xD4k1+1eUKdO3oM=
# SIG # End signature block
